# Generated by Django 6.0.4 on 2026-04-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('CREATE', 'Creacion'), ('UPDATE', 'Actualizacion'), ('DELETE', 'Eliminacion'), ('APPROVE', 'Aprobacion'), ('MOVE', 'Movimiento'), ('PUBLISH', 'Publicacion')], max_length=20),
        ),
    ]
