# Generated by Django 6.0.4 on 2026-06-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_auditlog_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMIN', 'Administrador'), ('JEFE', 'Jefe'), ('ENCARGADO_ACTIVOS', 'Encargado de Activos')], max_length=30),
        ),
    ]
