# Generated by Django 6.0.4 on 2026-04-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura_academica', '0002_alter_carreraunidadacademica_options_and_more'),
        ('guias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_activo', models.CharField(max_length=50, unique=True)),
                ('cantidad_total', models.IntegerField(default=0)),
                ('cantidad_buena', models.IntegerField(default=0)),
                ('cantidad_regular', models.IntegerField(default=0)),
                ('cantidad_mala', models.IntegerField(default=0)),
                ('estatus_general', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20)),
                ('ubicacion_sala', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('evaluado_en', models.DateTimeField(blank=True, null=True)),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_evaluados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo_activo'],
            },
        ),
        migrations.CreateModel(
            name='EquipoRequeridoPorGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_equipo_teorico', models.CharField(max_length=150)),
                ('cantidad_requerida', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_que_requieren', to='laboratorios.equipo')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_requeridos', to='guias.guia')),
            ],
            options={
                'verbose_name': 'Equipo requerido por guia',
                'verbose_name_plural': 'Equipos requeridos por guia',
                'ordering': ['guia', 'nombre_equipo_teorico'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('campus', models.CharField(max_length=100)),
                ('edificio', models.CharField(blank=True, max_length=50)),
                ('piso', models.SmallIntegerField(blank=True, null=True)),
                ('sala', models.CharField(max_length=50)),
                ('capacidad_estudiantes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='estructura_academica.unidadacademica')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='laboratorios.laboratorio'),
        ),
        migrations.CreateModel(
            name='LaboratorioAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_laboratorios', to='estructura_academica.asignatura')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_asignaturas', to='laboratorios.laboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio y asignatura',
                'verbose_name_plural': 'Laboratorios y asignaturas',
                'ordering': ['laboratorio', 'asignatura'],
                'unique_together': {('laboratorio', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='asignaturas',
            field=models.ManyToManyField(related_name='laboratorios', through='laboratorios.LaboratorioAsignatura', to='estructura_academica.asignatura'),
        ),
    ]
