# Generated by Django 6.0.4 on 2026-04-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text='Características técnicas del equipo en formato clave-valor', verbose_name='Especificaciones técnicas'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Enlace público a imagen alojada en la nube (Drive, S3, Cloudinary, etc.)', max_length=500, null=True, verbose_name='URL de foto del equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones, accesorios incluidos, condiciones especiales', null=True, verbose_name='Notas adicionales'),
        ),
    ]
