# Generated by Django 6.0.4 on 2026-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_equipo_especificaciones_equipo_foto_url_equipo_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='requiere_mantenimiento',
            field=models.BooleanField(default=False, help_text='Activar solo para equipos que requieren mantenimiento o calibración periódica (microscopios, balanzas, etc.)', verbose_name='Requiere mantenimiento periódico'),
        ),
    ]
