# Generated by Django 6.0.4 on 2026-05-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_laboratorio_jerarquia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='actividad_investigacion',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='actividad_pea',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='actividad_servicios',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='norma',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='normativa_infraestructura',
            field=models.CharField(blank=True, help_text='Norma de bioseguridad, calidad o reglamento institucional.', max_length=255, verbose_name='Normativa aplicable'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='usa_investigacion',
            field=models.BooleanField(default=False, verbose_name='Usa Investigación'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='usa_pea',
            field=models.BooleanField(default=False, verbose_name='Usa PEA'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='usa_venta_servicios',
            field=models.BooleanField(default=False, verbose_name='Usa Venta de Servicios'),
        ),
        migrations.CreateModel(
            name='UsoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.CharField(max_length=255)),
                ('semestre', models.CharField(blank=True, max_length=50)),
                ('carrera', models.CharField(blank=True, max_length=255)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_academicos', to='laboratorios.laboratorio')),
            ],
            options={
                'verbose_name': 'Uso Académico',
                'verbose_name_plural': 'Usos Académicos',
                'ordering': ['laboratorio', 'carrera', 'semestre', 'asignatura'],
            },
        ),
    ]
