# Generated by Django 6.0.4 on 2026-05-26 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0005_remove_laboratorio_actividad_investigacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='laboratorios.laboratorio'),
        ),
    ]
