# Generated by Django 6.0.4 on 2026-05-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0007_alter_carreraunidadacademica_options_and_more'),
        ('laboratorios', '0006_alter_equipo_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='estructura_academica.unidadacademica'),
        ),
    ]
