# Generated by Django 6.0.4 on 2026-06-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0007_equipo_unidad_academica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo canónico que agrupa esta unidad con otras equivalentes (#12).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='laboratorios.tipoequipo'),
        ),
        migrations.AddField(
            model_name='equiporequeridoporguia',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo canónico requerido por la guía (#12).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerido_por_guias', to='laboratorios.tipoequipo'),
        ),
    ]
