# Generated by Django 6.0.4 on 2026-06-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0009_backfill_tipoequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='normativa_infraestructura',
            field=models.TextField(blank=True, help_text='Norma de bioseguridad, calidad o reglamento institucional.', verbose_name='Normativa aplicable'),
        ),
    ]
