# Generated by Django 6.0.4 on 2026-06-12 03:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0007_alter_carreraunidadacademica_options_and_more'),
        ('laboratorios', '0010_alter_laboratorio_normativa_infraestructura'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='laboratorio',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('nombre'), models.F('parent'), models.F('unidad_academica'), name='uq_lab_nombre_parent_ua'),
        ),
        migrations.AddConstraint(
            model_name='laboratorio',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('nombre'), models.F('unidad_academica'), condition=models.Q(('parent__isnull', True)), name='uq_lab_raiz_nombre_ua'),
        ),
    ]
