# Generated by Django 6.0.4 on 2026-08-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0012_extension_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion_sala',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
