# Generated by Django 6.0.4 on 2026-04-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreraunidadacademica',
            options={'ordering': ['carrera', 'unidad_academica'], 'verbose_name': 'Carrera por unidad academica', 'verbose_name_plural': 'Carreras por unidades academicas'},
        ),
        migrations.RemoveConstraint(
            model_name='carreraunidadacademica',
            name='unique_carrera_unidad',
        ),
        migrations.RemoveConstraint(
            model_name='departamento',
            name='unique_departamento_codigo_unidad',
        ),
        migrations.AlterField(
            model_name='carreraunidadacademica',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas', to='estructura_academica.carrera'),
        ),
        migrations.AlterField(
            model_name='carreraunidadacademica',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='estructura_academica.unidadacademica'),
        ),
        migrations.AlterUniqueTogether(
            name='carreraunidadacademica',
            unique_together={('carrera', 'unidad_academica')},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('codigo', 'unidad_academica')},
        ),
    ]
