# Generated by Django 6.0.4 on 2026-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0002_alter_carreraunidadacademica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadacademica',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
