# Generated by Django 6.0.4 on 2026-04-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0003_unidadacademica_abreviacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreraunidadacademica',
            options={'ordering': ['carrera', 'unidad_academica'], 'verbose_name': 'Carrera por sede', 'verbose_name_plural': 'Carreras por sedes'},
        ),
        migrations.AddField(
            model_name='carrera',
            name='unidades_academicas',
            field=models.ManyToManyField(blank=True, related_name='carreras_m2m', through='estructura_academica.CarreraUnidadAcademica', to='estructura_academica.unidadacademica'),
        ),
        migrations.AlterField(
            model_name='carreraunidadacademica',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_sedes', to='estructura_academica.carrera'),
        ),
        migrations.AlterField(
            model_name='carreraunidadacademica',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sede_carreras', to='estructura_academica.unidadacademica'),
        ),
    ]
