# Generated by Django 6.0.4 on 2026-04-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0004_carrera_m2m_unidades_academicas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='estructura_academica.unidadacademica'),
        ),
        migrations.CreateModel(
            name='DepartamentoUnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depto_sedes', to='estructura_academica.departamento')),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sede_deptos', to='estructura_academica.unidadacademica')),
            ],
            options={
                'verbose_name': 'Departamento por sede',
                'verbose_name_plural': 'Departamentos por sedes',
                'ordering': ['departamento', 'unidad_academica'],
                'unique_together': {('departamento', 'unidad_academica')},
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidades_academicas',
            field=models.ManyToManyField(blank=True, related_name='departamentos_m2m', through='estructura_academica.DepartamentoUnidadAcademica', to='estructura_academica.unidadacademica'),
        ),
    ]
