# Generated by Django 6.0.4 on 2026-04-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0005_departamento_m2m_unidades_academicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='unidad_academica',
        ),
    ]
