# Generated by Django 6.0.4 on 2026-05-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_academica', '0006_remove_asignatura_unidad_academica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreraunidadacademica',
            options={'ordering': ['carrera', 'unidad_academica'], 'verbose_name': 'Carrera por Unidad Académica', 'verbose_name_plural': 'Carreras por Unidades Académicas'},
        ),
        migrations.AlterModelOptions(
            name='departamentounidadacademica',
            options={'ordering': ['departamento', 'unidad_academica'], 'verbose_name': 'Departamento por Unidad Académica', 'verbose_name_plural': 'Departamentos por Unidades Académicas'},
        ),
        migrations.AlterModelOptions(
            name='unidadacademica',
            options={'ordering': ['nombre'], 'verbose_name': 'Unidad Académica', 'verbose_name_plural': 'Unidades Académicas'},
        ),
    ]
