# Generated by Django 6.0.4 on 2026-05-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0003_equipo_requiere_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('limpieza', 'Limpieza y Desinfección'), ('reparacion', 'Reparación'), ('calibracion', 'Calibración'), ('verificacion', 'Verificación Técnica')], max_length=20)),
                ('estado', models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cancelado', 'Cancelado')], default='realizado', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField(verbose_name='Fecha de realización')),
                ('fecha_proximo', models.DateField(blank=True, null=True, verbose_name='Fecha del próximo servicio')),
                ('numero_certificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Certificado')),
                ('entidad_calibradora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entidad calibradora')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='laboratorios.equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Bitácora de Mantenimientos',
                'ordering': ['-fecha_realizacion'],
            },
        ),
    ]
