# Generated by Django 6.0.4 on 2026-04-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura_academica', '0002_alter_carreraunidadacademica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('numero_practica', models.SmallIntegerField()),
                ('portada_url', models.URLField(blank=True, max_length=500)),
                ('pdf_url', models.URLField(max_length=500)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('resolucion_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='estructura_academica.asignatura')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'ordering': ['asignatura', 'numero_practica'],
                'unique_together': {('asignatura', 'numero_practica')},
            },
        ),
    ]
