# Generated by Django 6.0.4 on 2026-05-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='motivo_rechazo',
        ),
    ]
