# Generated by Django 6.0.4 on 2026-08-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0002_remove_guia_aprobado_por_remove_guia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='pdf_archivo',
            field=models.FileField(blank=True, help_text='PDF de la guía de laboratorio alojado en el servidor.', null=True, upload_to='guias/pdf/', verbose_name='Archivo PDF de la guía'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Sólo para guías que aún no tienen el archivo subido.', max_length=500, verbose_name='URL externa del PDF'),
        ),
    ]
