# Generated by Django 6.0.4 on 2026-04-17 00:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reordenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_trasladada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField(blank=True)),
                ('resolucion_numero', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('ejecutado', 'Ejecutado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('pdf_reporte_url', models.URLField(blank=True, max_length=500)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reordenamientos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reordenamientos_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reordenamientos', to='laboratorios.equipo')),
                ('laboratorio_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reordenamientos_destino', to='laboratorios.laboratorio')),
                ('laboratorio_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reordenamientos_origen', to='laboratorios.laboratorio')),
            ],
            options={
                'verbose_name': 'Reordenamiento',
                'verbose_name_plural': 'Reordenamientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
