# Generated by Django 6.0.4 on 2026-05-26 02:18

import apps.reordenamiento.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0005_remove_laboratorio_actividad_investigacion_and_more'),
        ('reordenamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reordenamiento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reordenamientos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='documento_respaldo',
            field=models.FileField(blank=True, help_text='PDF para REASIGNACION; PDF/imagen opcionales para PRESTAMO y COMPRA.', null=True, upload_to=apps.reordenamiento.models._upload_documento, verbose_name='Documento de respaldo'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='fecha_retorno_prevista',
            field=models.DateField(blank=True, help_text='Obligatorio para movimientos tipo PRESTAMO.', null=True, verbose_name='Fecha de retorno prevista'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Obligatorio para REASIGNACION_DEFINITIVA.', max_length=100, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='observaciones_recepcion',
            field=models.TextField(blank=True, verbose_name='Observaciones de recepción'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='recepcionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reordenamientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('RESOLUCION', 'Resolución'), ('AUTORIZACION', 'Autorización'), ('FACTURA', 'Factura'), ('ACTA_ENTREGA', 'Acta de entrega'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='reordenamiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('REASIGNACION_DEFINITIVA', 'Reasignación definitiva'), ('PRESTAMO', 'Préstamo'), ('COMPRA', 'Compra')], default='REASIGNACION_DEFINITIVA', max_length=30, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='reordenamiento',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reordenamientos_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por (legacy)'),
        ),
        migrations.AlterField(
            model_name='reordenamiento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_transito', 'En tránsito'), ('recepcionado', 'Recepcionado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente (legacy)'), ('autorizado', 'Autorizado (legacy)'), ('ejecutado', 'Ejecutado (legacy)')], default='pendiente_aprobacion', max_length=25),
        ),
        migrations.AlterField(
            model_name='reordenamiento',
            name='laboratorio_origen',
            field=models.ForeignKey(blank=True, help_text='Requerido para REASIGNACION y PRESTAMO. Nulo para COMPRA.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reordenamientos_origen', to='laboratorios.laboratorio'),
        ),
        migrations.AlterField(
            model_name='reordenamiento',
            name='resolucion_numero',
            field=models.CharField(blank=True, help_text='Campo legacy mantenido por compatibilidad. Usa numero_documento.', max_length=50, verbose_name='Número de resolución (legacy)'),
        ),
    ]
