# Generated by Django 6.0.4 on 2026-04-19 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REORDENAMIENTO', 'Nuevo Reordenamiento Pendiente'), ('AUTORIZACION', 'Reordenamiento Autorizado'), ('EVALUACION', 'Equipo evaluado con estado crítico'), ('SISTEMA', 'Mensaje del sistema')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_url', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
