# Generated by Django 6.0.4 on 2026-04-27 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0002_equipo_especificaciones_equipo_foto_url_equipo_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_bueno', models.PositiveIntegerField(default=0, verbose_name='Unidades en buen estado')),
                ('cantidad_regular', models.PositiveIntegerField(default=0, verbose_name='Unidades en estado regular')),
                ('cantidad_malo', models.PositiveIntegerField(default=0, verbose_name='Unidades en mal estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones generales')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='laboratorios.equipo', verbose_name='Equipo evaluado')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='laboratorios.laboratorio', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
