# Generated by Django 6.0.4 on 2026-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_auth_url', models.URLField(blank=True)),
                ('modulo_reactivos_activo', models.BooleanField(default=False)),
                ('nombre_sistema', models.CharField(default='SGL - EMI', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
